Lesson3
LadyNoveria/ASP.NET_Core_Web_API pull request #4
Opened 2021-05-09 12:21 UTC by LadyNoveria

2021-05-15 19:14 UTC, Forkosigan requested changes

2021-05-15 19:14 UTC, Forkosigan commented on Lesson2.MetricsManager/Lesson2.MetricsManager/Controllers/AgentsController.cs
>  namespace Lesson2.MetricsManager.Controllers
Слова типа Lesson2 в реанльых проектах недопустимы. Причем тут Lesson2? Мы проект разрабтываем.

2021-05-15 19:14 UTC, Forkosigan commented on Lesson2.MetricsManager/Lesson2.MetricsManager/Controllers/AgentsController.cs
> +            _logger.LogInformation("api/agents/RegisterAgent");
Внимательнее с заданием - требуется логировать все параметры всех методов всех контроллеров и в менеджере и в агенте. От логирования просто пути толку мало

2021-05-15 19:14 UTC, Forkosigan commented on Lesson2.MetricsManager/MetricsAgent/Repositories/RamMetricsRepository.cs
> +        private const string ConnectionString = "Data Source=metrics.db;Version=3;Pooling=true;Max Pool Size=100";
это плохой стиль. строка соединения у вас копипастится в каждом контроллере. А что если мы захотим ее поменять? придется бегать по коду и искать все места где она есть. 
Либо ввести статический класс с публичной константой строкой соедеинения и ее везде юзать, либб сделать интерфейс IConnectionProvider{
   SQLiteConntectiob CreateOpenedConnection();
}

и в еще реализации сразу создавать
using var connection = new SQLiteConnection(ConnectionString);
            connection.Open();
и возвращать.
Далее этот интефрйес инъектровать во все репозитории и не забыть зарегать в DI

2021-05-15 19:14 UTC, Forkosigan commented on Lesson2.MetricsManager/MetricsAgent/Responses/AllDotNetMetricsResponse.cs
> +    public class DotNetMetricDto : MetricDto
в DTO стоит забыть о наследовании. Это плохая идея. Все DTO независимы даже если и похожи.

2021-05-15 19:14 UTC, Forkosigan commented on Lesson2.MetricsManager/MetricsAgent/Responses/MetricDto.cs
> +        public int Id { get; set; }
не думаю что клиенту нашего API нужен этот Id. У нас же не планируется в API операций в который бы его можно было бы заюзать извне (например удаление метрики по Id). В модели данных репозитория это полей окей, так как эта часть строки таблицы

2021-05-15 22:51 UTC, LadyNoveria commented on Lesson2.MetricsManager/MetricsAgent/Responses/MetricDto.cs
> +        public int Id { get; set; }
исправлено

2021-05-15 22:51 UTC, LadyNoveria commented on Lesson2.MetricsManager/MetricsAgent/Responses/AllDotNetMetricsResponse.cs
> +    public class DotNetMetricDto : MetricDto
исправлено

2021-05-15 22:53 UTC, LadyNoveria commented on Lesson2.MetricsManager/Lesson2.MetricsManager/Controllers/AgentsController.cs
>  namespace Lesson2.MetricsManager.Controllers
Проект создавался, когда еще было не понятно, что это полноценный проект и что он из себя представляет. Отсюда и название. Спасибо за замечание.

2021-05-15 23:30 UTC, LadyNoveria commented on Lesson2.MetricsManager/MetricsAgent/Repositories/RamMetricsRepository.cs
> +        private const string ConnectionString = "Data Source=metrics.db;Version=3;Pooling=true;Max Pool Size=100";
Создала класс ConnectionProvider, который реализует интерфейс IConnectionProvider:
public SQLiteConnection CreateOpenedConnection()
        {
            string ConnectionString = "Data Source=metrics.db;Version=3;Pooling=true;Max Pool Size=100";
            using var connection = new SQLiteConnection(ConnectionString);
            connection.Open();
            return connection;
        }

В StartUp зарегистрировала зависимость services.AddScoped<IConnectionProvider, ConnectionProvider>(). Исправила код во всех репозиториях агента на: 
        private ConnectionProvider _connectionProvider;
        private SQLiteConnection _connection;
        public void Create(CpuMetric item)
        {
            _connectionProvider = new ConnectionProvider();
            _connection = _connectionProvider.CreateOpenedConnection();
<...>

2021-05-17 11:06 UTC, LadyNoveria commented on Lesson2.MetricsManager/Lesson2.MetricsManager/Controllers/AgentsController.cs
> +            _logger.LogInformation("api/agents/RegisterAgent");
исправлено

2021-05-17 11:06 UTC, merged